# _config.yml

url: "https://AnthonyYsw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: "Siwei Yang" # the name of your site, e.g. ACME Corp.
description: Anthony's Original Blog

# language
lang: en_GB

theme: null
plugins:
  - jekyll-feed

